from typing import overload

@overload
def overloaded(x: int) -> None: ...
@overload
def overloaded(x: str) -> str: ...

class OverloadClass:
    @overload
    def overloaded(x: int) -> None: ...
    @overload
    def overloaded(x: str) -> str: ...
