[tool.black]
target_version = ['py36', 'py37', 'py38']
include = '\.py$'

exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
)/
'''

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
